services:
  mysql:
    image: mysql:8.0
    container_name: auth_service_db_local
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_service
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - auth_network

volumes:
  mysql_data:
    name: auth_service_mysql_data

networks:
  auth_network:
    name: auth_service_network